apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: flask-app-test
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: pywebapp.com
    http:
       paths:
       - backend:
            serviceName: servicepy.yaml
            servicePort: 80
