apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8_app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: pywebapp.com
    http:
       paths:
       - backend:
            serviceName: k8sapp
            servicePort: 80
